identifier_fb: '615095708575325'
secret_fb: '6809e8114e5df58359b2757deede6029'
identifier_tw: 'Gr4leTgf50nAXgpFGyzmEbo7o'
secret_tw: 'fIYp5Cm0OMPCLfaMdJoyU6ptQoEaUoYAPoqgOiGw70l4OuQzMC'
identifier_gg: '776282675587-93n2kpe06vik2alomfpkcve77r2g9okv.apps.googleusercontent.com'
secret_gg: 'CcdcWUTflyrmHh77yiWN3VRb'
identifier_gg_local: '763337293862-pcruu8kkagfvqq9868unua8go28clsg3.apps.googleusercontent.com'
secret_gg_local: 'R6yZ-Ldlu6DrJLa6ziD20b5i'

